environments:
  default:
    kubeContext: k3d-demo
---
environments:
  {{ .Environment.Name }}:
    kubeContext: "{{ .Environment.KubeContext }}"
    missingFileHandler: Debug
    secrets:
      - ./config/{{ .Environment.Name }}-secrets.yaml
    values:
      - ./config/{{ .Environment.Name }}-values.yaml
